---
- name: Organization firmware upgrade
  hosts: meraki_servers
  gather_facts: false

  vars:
    test_org_id: "{{ lookup('env','MERAKI_ORG_ID') }}"
  tasks:
    # - name: Return identity of current API user
    #   cisco.meraki.administered_identities_me_info:
    #   register: current_user

    # - name: Gather Meraki Organizations
    #   cisco.meraki.organizations_info:
    #   register: org_response

    # - name: Store just the list of organizations
    #   ansible.builtin.set_fact:
    #     organizations: "{{ org_response.meraki_response }}"

    - name: Get networks in the organization
      cisco.meraki.networks_info:
        organizationId: "{{ test_org_id }}"
      register: org_networks

    - name: Set networkId fact for testing
      # This is just for testing purposes, to avoid looping through all networks
      ansible.builtin.set_fact:
        test_network_id: "{{ org_networks.meraki_response[1].id }}"

    - name: Get firmware versions for each network
      cisco.meraki.networks_firmware_upgrades_info:
        networkId: "{{ item.id }}"
      loop: "{{ org_networks.meraki_response }}"
      register: org_network_firmware_versions

    - name: Build dictionary of firmware versions by network
      ansible.builtin.set_fact:
        firmware_by_network: >-
          {{ dict(
               org_network_firmware_versions.results
                 | map(attribute='item.id')
                 | zip(
                     org_network_firmware_versions.results
                       | map(attribute='meraki_response')
                   )
             ) }}

    - name: Get network firmware versions
      cisco.meraki.networks_firmware_upgrades_info:
        networkId: "{{ test_network_id }}"
      register: network_firmware_versions

    - name: Create test_network_current_version dictionary with shortName and releaseType
      ansible.builtin.set_fact:
        test_network_current_version: >-
          "{{ firmware_by_network.L_655836695735845620.products.wireless.currentVersion.shortName }}" :
          "{{ firmware_by_network.L_655836695735845620.products.wireless.currentVersion.releaseType }}"

