---
- name: Gather Meraki Organizations
  hosts: meraki_servers
  gather_facts: no
  collections:
    - cisco.meraki
  vars:
    test_org_id: "{{ lookup('env','MERAKI_ORG_ID') }}"
  tasks:
    - name: Return identity of current API user
      administered_identities_me_info:
      register: current_user

    - name: Show retrieved user
      debug:
        var: current_user

    - name: Gather Meraki Organizations
      organizations_info:
      register: org_response

    - name: Store just the list of organizations
      set_fact:
        organizations: "{{ org_response.meraki_response }}"

    - name: Show retrieved organizations
      debug:
        var: organizations

    - name: Get networks in the organization
      networks_info:
        organizationId: "{{ test_org_id }}"
      register: org_networks
