- name: Ensure iperf3 is installed
  ansible.builtin.package:
    name: iperf3
    state: present

- name: Start iperf3 server on pi5 (wired, async)
  delegate_to: pi5
  become: true
  async: 40
  poll: 0
  ansible.builtin.shell: >
    iperf3 -s -B {{ iperf3_tests[0].server_bind }} --one-off --json > /tmp/iperf3_server_wired_to_wired.json

- name: Wait for iperf3 server to be ready
  ansible.builtin.wait_for:
    host: "{{ iperf3_tests[0].server_bind }}"
    port: 5201
    timeout: 10
  delegate_to: pi5

- name: Run iperf3 client (wired -> wired)
  delegate_to: pi4
  ansible.builtin.shell: >
    iperf3 -c {{ iperf3_tests[0].server_bind }} -B {{ iperf3_tests[0].client_bind }} -t 15 -P 8 --json
  register: iperf3_wired_to_wired_result
  changed_when: false

- name: Cleanup iperf3 server after test
  delegate_to: pi5
  become: true
  shell: |
    pkill -f "iperf3"
  ignore_errors: true

- name: Set fact for iperf3 wired to wired result (for use in init.yml)
  set_fact:
    iperf3_wired_to_wired_output: "{{ iperf3_wired_to_wired_result.stdout | from_json }}"
