- name: Ensure iperf3 is installed on all Raspberry Pi devices
  hosts: raspberry_pi
  become: true
  gather_facts: true

  vars:
    pi_interfaces:
      pi4:
        wired: 10.20.100.94
        wireless: 10.20.200.142
      pi5:
        wired: 10.20.100.91
        wireless: 10.20.200.240

  tasks:
    - name: Ensure iperf3 is installed
      ansible.builtin.package:
        name: iperf3
        state: present
